---
title: "Potential Recommenders"
output: html_notebook
---


```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(magrittr)
library(openxlsx)
library(tidytext)
library(textcat)
```


```{r}
sheet_names = readxl::excel_sheets("./citations.xlsx")
```

```{r}
citation_df = data.frame(citation = as.character(), paper = as.character())
for (i in 1:length(sheet_names)){
  citation_df %<>% 
    bind_rows(readxl::read_xlsx(path = "./citations.xlsx",
                                progress = TRUE,
                                sheet = sheet_names[i],
                                col_names = "citation") %>% 
                mutate(paper = as.character(sheet_names[i]),
                       citation = as.character(citation)))
}

str(citation_df)
```


```{r}
write.xlsx(x = citation_df, file = "complete_citation.xlsx")
```



```{r}
citation_df %<>% 
  separate(col = citation, sep = '"',into = c('authors','citing_paper','journal')) 
```

```{r}
citation_df$authors = str_replace_all(string = citation_df$authors, pattern = c("[:digit:]"),'')
citation_df$authors = str_replace(string = citation_df$authors, pattern = c("."),'')
citation_df$authors = str_trim(citation_df$authors,side = "left")
```

```{r}
save.image(file = "./citation.RData")
```


## Analyze Authors   

```{r}
write.xlsx(x = citation_df, file = "complete_citation.xlsx")
```


```{r}
author_freq_df = citation_df %>% 
  select(paper, citing_paper,text = authors) %>% 
  distinct() %>% as_tibble() %>% 
  unnest_tokens(word, text) %>% 
  anti_join(stop_words, by = "word")

author_freq_df %>% 
  group_by(word) %>% 
  summarize(COUNT = n()) %>% 
  ungroup() %>% 
  arrange(-COUNT)
```


```{r}
custom_stop_words <- bind_rows(tibble(word = c("al","diss","biodiesel","university","production","microwave"),
                                          lexicon = c("custom")),
                               stop_words)

custom_stop_words
```


```{r}
author_freq_df = author_freq_df %>% 
  anti_join(custom_stop_words, by = "word")

author_freq_df %>% 
  group_by(word) %>% 
  summarize(COUNT = n()) %>% 
  ungroup() %>% 
  arrange(-COUNT)
```


```{r}
author_freq_df3 = citation_df %>% 
  select(paper, citing_paper,text = authors) %>% 
  distinct() %>% as_tibble() %>% 
  unnest_tokens(word, text, token = "ngrams", n = 3) %>% 
  anti_join(stop_words, by = "word")

author_freq_df3 %>%
  count(word, sort = TRUE)

author_freq_df %>% 
  group_by(word) %>% 
  summarize(COUNT = n()) %>% 
  ungroup() %>% 
  arrange(-COUNT)
```


```{r}
citation_df[(str_detect(string = tolower(citation_df$authors), pattern = "mcgee")), ]
```

```{r}
citation_df %<>% 
  mutate(language = textcat(citing_paper)) %>% 
  filter(language %in% c('english'))
```


```{r}
getCitationPaper <- function(keyword,df=citation_df){
  library(dplyr)
  library(magrittr)
  library(textcat)
  
  df1 = df[(str_detect(string = tolower(df$authors), pattern = keyword)), ] %>% 
    select(paper,citing_paper) %>% 
    as_tibble() %>% 
    filter(!is.na(paper))
  
  df1 = df1[!duplicated(df1$paper),]
  return(df1)
  }

```



```{r}
getCitationPaper(keyword = "mcgee")
```

